/**
  * Each new term in the Fibonacci sequence is generated by adding the previous
  * two terms. By starting with 1 and 2, the first 10 terms will be:
  *
  * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  *
  * By considering the terms in the Fibonacci sequence whose values do not
  * exceed four million, find the sum of the even-valued terms.
*/
public class QuestionTwo {
    public static void main(String[] args) {
        int evenFibTotal = 0;
        int fibValue = 0;
        while (fibValue < 4000000) {
            if (fibValue % 2 == 0) {
                evenFibTotal += fibValue;
            }
            fibValue = FibStream.getNext();
        }
        System.out.println(evenFibTotal);
    }
}

// The class below belongs in its own file FibStream.java
// public class FibStream {
//     public static int fib = 1;
//     public static int previous = 0;
//
//     public static int getNext() {
//         if (fib == 1 && previous == 0) {
//             previous = fib;
//             return fib;
//         }
//         else {
//             int tempHolding = previous;
//             previous = fib;
//             fib += tempHolding;
//             return fib;
//         }
//     }
// }
